### PR TITLE
convert values of false to 0 and true to 1

### PR DESCRIPTION
**Pull request by patrick-troy**
These are the only categories that have multiple results meaning the same thing so have been converted to one standard format

### CODE REVIEW

**Review by MichaelHanksSF — CHANGES_REQUESTED** [review]
Happy with this, but small change, can we add FALSE and TRUE as acceptable options in the Schema please?

**Review by MichaelHanksSF — CHANGES_REQUESTED** [review]
I don't think this works as written. Though FALSE and TRUE are in the schema, they're not dealt with in the convertor?

When I run a file with FALSE in a yesno field it gets removed still as invalid.

**Comment by patrick-troy** [comment]
Which field are you changing to FALSE? I've just tested it with ReferralNFA and ICPCnotRequired (the only yesnotype nodes) and it seemed to work.
The converter just looks for any yesnotype node and converts them to lowercase so FALSE and false should work in the same way

**Comment by MichaelHanksSF** [comment]
Ah, I think that it is converting the FALSE to 0, but the error message is still being created. 
[CIN_Census_2021_FALSE_error_log_2022-10-04T110249Z.txt](https://github.com/SocialFinanceDigitalLabs/liia-tools/files/9714182/CIN_Census_2021_FALSE_error_log_2022-10-04T110249Z.txt)

Can we amend the error logs so that this isn't flagged as an error anymore?

**Review by MichaelHanksSF — APPROVED** [review]

**Pull request merged**
